print("jangan lari saya incer muka kamu")
print("halo rapi")
print("janji ga cepu")
print("awoakwoakwow")
print("jangan nongkrong trus")
print("kenalin nama gua rapi")
print("udh istirahat kak")
print("pulangnya jam brp kak")
print("kakanya cantik boleh ngga jadi pcr aku")
print("janji ga panik")